name: gv agency
on:
  push: 
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Latest Code
        run: |
          cd /home/ubuntu/gv-agency
          git pull origin master

      - name: Deploy static site
        run: |
          # Example: copy files to your web server directory (e.g. nginx)
          sudo cp -r /home/ubuntu/github-action-ci-cd/* /var/www/html/
